services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    network_mode: bridge
    ports:
      - 5000:5000
    restart: unless-stopped
volumes:
  changedetection-data: null
networks: {}
