version: '3.3'
services:
    firefox:
        ports:
            - 6901:6901
        environment:
            - VNC_PW=password
        container_name: kasmweb-firefox-1
        image: kasmweb/firefox:1.13.0
        restart: unless-stopped
