services:
  spotify-buddylist:
    ports:
      - 10000:10000
    volumes:
      - ./activity.db:/activity.db
    container_name: spotify-buddylist
    environment:
      - SP_DC=${SP_DC}
    image: benonymity/spotify-buddylist:latest
    network_mode: bridge
    restart: unless-stopped
networks: {}
