version: '3.3'
services:
    check-mk-raw:
        ports:
            - '5000:5000'
        tmpfs: '/opt/omd/sites/cmk/tmp:uid=1000,gid=1000'
        volumes:
            - /omd/sites
            - '/etc/localtime:/etc/localtime:ro'
        container_name: monitoring
        restart: unless-stopped
        image: checkmk/check-mk-raw
        network_mode: bridge
