services:
  wallos:
    container_name: wallos
    image: ghcr.io/ellite/wallos:latest
    ports:
      - 8282:80/tcp
    environment:
      TZ: europa/amsterdam
    # Volumes store your data between container upgrades
    volumes:
      - ./db:/var/www/html/db
      - ./logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
    network_mode: bridge
networks: {}
