---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
#    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europa/Amsterdam
      - SUBDOMAINS=#fill this one in ----------
      - TOKEN=#fill this one in ----------
#      - UPDATE_IP=ipv4 #optional
#      - LOG_FILE=false #optional
#    volumes:
#      - /path/to/appdata/config:/config #optional
    restart: unless-stopped
    network_mode: bridge
