services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europa/Amsterdam
      - SUBDOMAINS=$SUBDOMAINS
      - TOKEN=$TOKEN
      - LOG_FILE=true #optional
    volumes:
      - ./config:/config #optional
    restart: unless-stopped
    network_mode: bridge
networks: {}
