services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Amsterdam
      - CLI_ARGS= #optional
    volumes:
      - /docker/docker-setup/duplicati/config:/config
      - /backup:/backups
      - /docker/:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    #if using nginxproxymanager exclude: /docker-setup/nginxproxymanager/letsencrypt
    network_mode: bridge
networks: {}
