---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Home Network:
    - Test
        description: Arris TG2492LG
    - Ziggo Connectbox: 
        description: Arris TG2492LG
        href: http://192.168.0.1/
        icon: http://192.168.0.21:8096/storage/icons/router.svg
    - MikroTik RB260G:
        description: Switch
        href: http://192.168.0.5/
        ping: http://192.168.0.5/
        icon: http://192.168.0.21:8096/storage/icons/router.svg
    - HP Envy 4520:
        href: http://192.168.0.15/
        icon: https://apps.heimdall.site/storage/icons/printer.png
    - Dockge:
        href: http://192.168.0.21:5001
        ping: http://192.168.0.21:5001
        icon: https://raw.githubusercontent.com/louislam/dockge/master/frontend/public/icon.svg
    - Portainer:
        href: https://192.168.0.21:9443
        ping: https://192.168.0.21:9443
        icon: portainer
    - Pi-Hole:
        href: http://192.168.0.21/admin/
        ping: http://192.168.0.21/admin/
        icon: pi-hole
        widget:
          type: pihole
          url: http://192.168.0.21/
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
    - Wetty:
       href: http://192.168.0.21:3000/wetty/
       ping: http://192.168.0.21:3000/wetty/
       icon: https://apps.heimdall.site/storage/icons/wetty.png

- Monitoring:
    - NetData:
        description: A distributed, real-time, performance and health monitoring platform for systems, hardware, containers and applications
        href: https://app.netdata.cloud/spaces/netdata-cloud-space-x01oyh4/rooms/all-nodes/dashboards/main?utm_source=website&utm_content=top_navigation_sign_in#metrics_correlation=false&after=-900&before=0&utc=Europe%2FAmsterdam&offset=%2B2&timezoneName=Amsterdam%2C%20Berlin%2C%20Bern%2C%20Rome%2C%20Stockholm%2C%20Vienna&modal=&modalTab=&modalParams=&selectedIntegrationCategory=deploy.operating-systems
        icon: netdata
#    - Cadvisor:
#        description: Container Advisor
#        href: http://192.168.0.21:8888/containers/
#        ping: http://192.168.0.21:8888/containers/
#        icon: "https://raw.githubusercontent.com/101br03k/docker-setup/main/logo's/cadvisor.png"
    - Dozzle:
        description: A lightweight, web-based Docker log viewer that provides real-time monitoring and easy troubleshooting.
        href: http://192.168.0.21:9999
        ping: http://192.168.0.21:9999
        icon: dozzle
    - Glances:
        description: A monitoring tool which aims to present information through a curses or Web based interface.
        href: http://192.168.0.21:61208
        ping: http://192.168.0.21:61208
        icon: glances
    - Speedtest-tracker:
        description: Speedtest-tracker and database
        href: http://192.168.0.21:8080
        ping: http://192.168.0.21:8080
        icon: speedtest-tracker
        widget:
          type: speedtest
          url: http://192.168.0.21:8080
          fields: ["download", "upload", "ping"]
    - Watch Your Lan:
        description: Lan Monitor
        href: http://192.168.0.21:8840
        ping: http://192.168.0.21:8840
        icon: https://raw.githubusercontent.com/101br03k/docker-setup/main/logo's/WatchYourLan.png
    - Uptime Kuma:
        href: http://192.168.0.21:3001
        ping: http://192.168.0.21:3001
        icon: uptime-kuma

- Media:
    - Qbittorrent:
        href: http://192.168.0.22:18080
        ping: http://192.168.0.22:18080
        icon: qbittorrent
        widget:
          type: qbittorrent
          url: http://192.168.0.22:18080
    - Prowlarr:
        description: An indexer manager made integrate with your PVR apps.
        href: http://192.168.0.22:9696
        ping: http://192.168.0.22:9696
        icon: prowlarr
    - Sonarr:
        description: Series management
        href: http://192.168.0.22:8989
        ping: http://192.168.0.22:8989
        icon: sonarr
    - Radarr:
        description: Movie management
        href: http://192.168.0.22:7878
        ping: http://192.168.0.22:7878
        icon: radarr
    - Readarr:
        description: Ebooks management
        href: http://192.168.0.22:8787
        ping: http://192.168.0.22:8787
        icon: readarr
    - Lidarr:
        description: Music management
        href: http://192.168.0.22:8686
        ping: http://192.168.0.22:8686
        icon: lidarr
    - Bazarr:
        description: Subtitle management
        href: http://192.168.0.22:6767
        ping: http://192.168.0.22:6767
        icon: bazarr

- Tools:
    - Duplicati:
        href: http://192.168.0.21:8200
        ping: http://192.168.0.21:8200
        icon: duplicati
    - Duplicati Monitoring:
        href: https://www.duplicati-monitoring.com/overview
        icon: duplicati
    - Vscode web editor: 
        href: http://192.168.0.21:5443/?folder=/docker-setup
        ping: http://192.168.0.21:5443
        icon: vscode
    - OnlyOffice DocumentServer: 
        href: http://192.168.0.21:62442/example/?userid=uid-1&lang=en&directUrl=false
        ping: http://192.168.0.21:62442/example/?userid=uid-1&lang=en&directUrl=false
        icon: onlyoffice
    - TwingateVPN:
        href: https://adrieit.twingate.com/
        icon: twingate
    - nginx-proxy-manager:
        href: http://192.168.0.21:181
        ping: https://192.168.0.21:180
        icon: nginx-proxy-manager
    - Crontab-UI: 
        href: http://192.168.0.21:8656
        ping: http://192.168.0.21:5443
#        icon: cron

- Overig:
    - Kasmweb/Firefox1:
        description: Firefox container 1
        href: https://192.168.0.21:6901
        ping: https://192.168.0.21:6901
        icon: https://raw.githubusercontent.com/101br03k/docker-setup/5db41c6fc85ce3f83abebf28e74b5b4bbaeba319/logo's/firefox-logo-1000x1032.png
    - Kasmweb/Firefox2:
        description: Firefox container 1
        href: https://192.168.0.21:6902
        ping: https://192.168.0.21:6902
        icon: https://raw.githubusercontent.com/101br03k/docker-setup/5db41c6fc85ce3f83abebf28e74b5b4bbaeba319/logo's/firefox-logo-1000x1032.png

- Graphs:
   - Pi-Hole:
        href: http://192.168.0.21/admin/
        ping: http://192.168.0.21/admin/
        icon: pi-hole
        widget:
          type: pihole
          url: http://192.168.0.21/
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
   - Speedtest-tracker:
        description: Speedtest-tracker and database
        href: http://192.168.0.21:8080
        ping: http://192.168.0.21:8080
        icon: speedtest-tracker
        widget:
          type: speedtest
          url: http://192.168.0.21:8080
          fields: ["download", "upload", "ping"]
   - Uptime Kuma:
        href: http://192.168.0.21:3001
        ping: http://192.168.0.21:3001
        icon: uptime-kuma
        widget:
          type: uptimekuma
          url: http://192.168.0.21:3001
          slug: wan
          fields: ["up", "down", "uptime", "incident"]
   - Qbittorrent:
           href: http://192.168.0.22:18080
           ping: http://192.168.0.22:18080
           icon: qbittorrent
           widget:
             type: qbittorrent
             url: http://192.168.0.22:18080

- Glances:
   - Glances:
       description: A monitoring tool which aims to present information through a curses or Web based interface.
       href: http://192.168.0.21:61208
       ping: http://192.168.0.21:61208
       icon: glances
       widget:
         type: glances
         url: http://192.168.0.21:61208
         metric: info
   - CPU Usage:
       widget:
         type: glances
         url: http://192.168.0.21:61208
         metric: cpu
         chart: false
   - Memory Usage:
       widget:
         type: glances
         url: http://192.168.0.21:61208
         metric: memory
         chart: false
   - Process Usage:
       widget:
         type: glances
         url: http://192.168.0.21:61208
         metric: process
   - Network Usage:
       widget:
         type: glances
         url: http://192.168.0.21:61208
         metric: network:eth0
         chart: false
