version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=1000 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /docker/docker-setup/config:/config # Configuration directory
      - /docker/docker-setup/tvshows:/mnt/share1 # Media directory
      - /docker/docker-setup/media:/mnt/share2 # Media directory
    ports:
      - 8196:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped
    network_mode: bridge
