version: "2.1"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/config/openvpn:/config
    ports:
      - 943:943
      - 9444:9443
      - 1194:1194/udp
    restart: unless-stopped
    network_mode: bridge
