services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3006:3000
    volumes:
      - /docker/homepage-config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_VAR_USERNAME=$HOMEPAGE_VAR_USERNAME
      - HOMEPAGE_VAR_MAIL=$HOMEPAGE_VAR_MAIL
      - HOMEPAGE_VAR_PASSWORD=$HOMEPAGE_VAR_PASSWORD
      - HOMEPAGE_VAR_CHANGEDETECTION_KEY=$HOMEPAGE_VAR_CHANGEDETECTION_KEY
      - HOMEPAGE_VAR_UPTIMEROBOT_KEY=$HOMEPAGE_VAR_UPTIMEROBOT_KEY
      - HOMEPAGE_VAR_PIHOLE_API_100_DOCKER=$HOMEPAGE_VAR_PIHOLE_API_100_DOCKER
      - HOMEPAGE_VAR_PROXMOX_API_TOKEN_ID=$HOMEPAGE_VAR_PROXMOX_API_TOKEN_ID
      - HOMEPAGE_VAR_PROXMOX_API_TOKEN_SECRET=$HOMEPAGE_VAR_PROXMOX_API_TOKEN_SECRET
      - HOMEPAGE_VAR_LINKWARDEN_KEY=$HOMEPAGE_VAR_LINKWARDEN_KEY
    restart: unless-stopped
    network_mode: bridge
networks: {}
