services:
  wetty:
    container_name: wetty
    command:
    - --ssh-host=192.168.0.20
    image: wettyoss/wetty
    ports:
    - 3000:3000
    restart: unless-stopped
    network_mode: bridge
version: '3'
