version: '3.5'
services:
  dash:
    container_name: dashdot
    environment:
     DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: 'true'
     DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'
     DASHDOT_USE_IMPERIAL: 'false'
     DASHDOT_ENABLE_CPU_TEMPS: 'true'
     DASHDOT_SHOW_HOST: 'true'
     DASHDOT_ACCEPT_OOKLA_EULA: 'true'
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '3003:3001'
    volumes:
      - /:/mnt/host:ro
