services:
  firefox:
    image: ghcr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Amsterdam
    volumes:
      - ./config:/config
    network_mode: bridge
    ports:
      - 6901:3000
      - 6902:3001
    shm_size: 1gb
    restart: unless-stopped
networks: {}
