version: '3'

services:
  magicmirror:
    container_name: magic-mirror
    image: karsten13/magicmirror:latest
    ports:
      - "8070:8080"
    volumes:
      - ../mounts/config:/opt/magic_mirror/config
      - ../mounts/modules:/opt/magic_mirror/modules
      - ../mounts/css:/opt/magic_mirror/css
    restart: unless-stopped
    command: 
      - npm
      - run
      - server
