version: '3.3'
services:
    kasmweb1:
        ports:
            - 6901:6901
        environment:
            - VNC_PW=password
        container_name: kasmweb-firefox-1
        image: kasmweb/firefox:latest'
        restart: unless-stopped
        
    kasmweb2:
        ports:
            - 6902:6901
        environment:
            - VNC_PW=password
        container_name: kasmweb-firefox-2
        image: 'kasmweb/firefox:latest'
        restart: unless-stopped
