services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /docker/docker-setup/:/docker/docker-setup/
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/docker/docker-setup/
    network_mode: bridge
networks: {}
